[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sphere-image-processor"
version = "0.0.1"
authors = [
  { name = "Ryuto Yoshida" },
]
description = "Spherical image processing with OpenCV, integrated with rotation and geometry helpers."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "opencv-contrib-python",
    "matplotlib",
    "units @ git+https://github.com/ry-yoshida-dev/Units.git",
    "rotation @ git+https://github.com/ry-yoshida-dev/Rotation.git",
    "handedness-rotation @ git+https://github.com/ry-yoshida-dev/HandednessRotation.git",
    "geometry @ git+https://github.com/ry-yoshida-dev/Geometry.git",
]

[dependency-groups]
dev = [
    "ipykernel",
]

[tool.uv]
default-groups = ["dev"]

[project.urls]
Homepage = "https://github.com/ry-yoshida-dev/SphereImageProcessor"
"Bug Tracker" = "https://github.com/ry-yoshida-dev/SphereImageProcessor/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sphere_image_processor = ["py.typed"]
